import { mkdir, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import process from 'node:process'
import { applyPublicApiUpdate, checkPublicApi, formatPublicApiReport, planPublicApiUpdate } from '@icebreakers/monorepo'
import path from 'pathe'
import { describe, expect, it } from 'vitest'
import { build, cli, config, setup, snapshot, source } from './fixture'

describe('public API reports from the real built declaration output', () => {
  it('reports only public signatures, preserves check inputs and explicitly applies/idempotently reuses a plan', async () => {
    const root = await setup()
    const before = await snapshot(root)
    const plan = await planPublicApiUpdate(root)
    expect(plan.report.status).toBe('changes')
    expect(plan.report.entries[0]).toMatchObject({ status: 'new', changeIntents: [] })
    expect(plan.report.entries[0]!.after).toContain('greet(name: string): string')
    expect(plan.report.entries[0]!.after).not.toContain('internalSecret')
    expect(plan.report.entries[0]!.diff).toContain('--- /dev/null')
    expect(await snapshot(root)).toEqual(before)
    expect(await applyPublicApiUpdate(root, plan)).toMatchObject({ status: 'applied', changed: ['etc/sdk.api.md'] })
    expect(await applyPublicApiUpdate(root, plan)).toMatchObject({ status: 'unchanged', changed: [] })
    const report = await checkPublicApi(root)
    expect(report.status).toBe('unchanged')
    expect(report.review).toContain('SemVer')
    await writeFile(path.join(root, 'packages/sdk/src/index.ts'), source.replace('hi ', 'hello '))
    await build(root)
    expect((await checkPublicApi(root)).status).toBe('unchanged')
  })

  it('reports additions, removals, parameter/return changes and independent subpath baselines with active intents', async () => {
    const root = await setup()
    await config(root, { '.': { entryPoint: 'dist/index.d.ts', baseline: 'etc/sdk.api.md' }, './feature': { entryPoint: 'dist/feature.d.ts', baseline: 'etc/feature.api.md' } })
    await applyPublicApiUpdate(root, await planPublicApiUpdate(root))
    await mkdir(path.join(root, '.changeset'))
    await writeFile(path.join(root, '.changeset/api.md'), '---\n"@test/sdk": minor\n---\nReview changed API.\n')
    await writeFile(path.join(root, 'packages/sdk/src/index.ts'), '/** @public */\nexport function greet(id: number): number { return id }\n/** @public */\nexport const added: string = "new"\n')
    await writeFile(path.join(root, 'packages/sdk/src/feature.ts'), '/** @public */\nexport interface Replacement { count: number }\n')
    await build(root)
    const report = await checkPublicApi(root)
    expect(report.entries.map(entry => entry.status)).toEqual(['changed', 'changed'])
    expect(report.entries[0]!.diff).toContain('+export function greet(id: number): number;')
    expect(report.entries[1]!.diff).toContain('-export interface Feature')
    expect(report.entries.every(entry => entry.changeIntents.includes('.changeset/api.md'))).toBe(true)
    expect(formatPublicApiReport(report)).toContain('etc/feature.api.md')
    await writeFile(path.join(root, '.changeset/ledger.yaml'), '"@test/sdk@1.1.0":\n  dir: packages/sdk\n  intents: [api]\n')
    expect((await checkPublicApi(root)).entries.every(entry => entry.changeIntents.length === 0)).toBe(true)
  })

  it('rejects stale declarations, baseline and configuration while preserving unrelated files', async () => {
    const root = await setup()
    const initial = await planPublicApiUpdate(root)
    await writeFile(path.join(root, 'packages/sdk/dist/index.d.ts'), '/** @public */\nexport declare const revised: number;\n')
    await expect(applyPublicApiUpdate(root, initial)).rejects.toThrow('changed')
    const next = await planPublicApiUpdate(root)
    await mkdir(path.join(root, 'etc'))
    await writeFile(path.join(root, 'etc/sdk.api.md'), 'Business notes must survive.\n')
    const before = await snapshot(root)
    await expect(applyPublicApiUpdate(root, next)).rejects.toThrow('changed')
    expect(await snapshot(root)).toEqual(before)
    await rm(path.join(root, 'etc/sdk.api.md'))
    const fresh = await planPublicApiUpdate(root)
    await config(root, { '.': { entryPoint: 'dist/index.d.ts', baseline: 'etc/different.api.md' } })
    await expect(applyPublicApiUpdate(root, fresh)).rejects.toThrow('changed')
  })

  it('skips unconfigured packages, diagnoses missing local tools and missing build artifacts without installing', async () => {
    const root = await setup({ config: false, tool: false })
    expect((await checkPublicApi(root)).status).toBe('skipped')
    await config(root)
    const before = await snapshot(root)
    expect((await checkPublicApi(root))).toMatchObject({ status: 'failed', diagnostics: [{ code: 'api-tool-unavailable' }] })
    expect(await snapshot(root)).toEqual(before)
    const built = await setup()
    await rm(path.join(built, 'packages/sdk/dist'), { recursive: true })
    expect((await checkPublicApi(built)).entries[0]).toMatchObject({ status: 'failed', diagnostics: [{ code: 'api-analysis-failed' }] })
  })

  it('rejects duplicate, nonpublic, traversal and linked baseline targets', async () => {
    const root = await setup()
    await config(root, { '.': { entryPoint: 'dist/index.d.ts', baseline: 'etc/sdk.api.md' }, './feature': { entryPoint: 'dist/feature.d.ts', baseline: 'etc/SDK.api.md' } })
    await expect(checkPublicApi(root)).rejects.toThrow('distinct')
    await config(root, { './hidden': { entryPoint: 'dist/index.d.ts', baseline: 'etc/sdk.api.md' } })
    expect((await checkPublicApi(root)).entries[0]!.diagnostics[0]!.message).toContain('not a literal public')
    await config(root, { '.': { entryPoint: 'dist/index.d.ts', baseline: '../sdk.api.md' } })
    await expect(checkPublicApi(root)).rejects.toThrow('Unsafe')
    await config(root)
    await mkdir(path.join(root, 'outside'))
    await symlink(path.join(root, 'outside'), path.join(root, 'etc'), process.platform === 'win32' ? 'junction' : 'dir')
    expect((await checkPublicApi(root)).entries[0]!.status).toBe('failed')
  })

  it('preserves CRLF baselines on unchanged API checks and honors exact package selection', async () => {
    const root = await setup()
    await applyPublicApiUpdate(root, await planPublicApiUpdate(root))
    const filename = path.join(root, 'etc/sdk.api.md')
    await writeFile(filename, (await readFile(filename, 'utf8')).replaceAll('\n', '\r\n'))
    const before = await snapshot(root)
    expect((await checkPublicApi(root, { packages: ['@test/sdk'] })).status).toBe('unchanged')
    await applyPublicApiUpdate(root, await planPublicApiUpdate(root))
    expect(await snapshot(root)).toEqual(before)
    await expect(checkPublicApi(root, { packages: ['missing'] })).rejects.toThrow()
  })

  it('provides read-only CLI exit codes, portable JSON plans and explicit apply', async () => {
    const root = await setup()
    const before = await snapshot(root)
    const check = cli(root, ['check', '--json'])
    expect(check.status, check.stderr).toBe(1)
    expect(JSON.parse(check.stdout).status).toBe('changes')
    const preview = cli(root, ['update', '--json'])
    expect(preview.status, preview.stderr).toBe(0)
    expect(await snapshot(root)).toEqual(before)
    await writeFile(path.join(root, 'plan.json'), preview.stdout)
    const apply = cli(root, ['update', '--apply', 'plan.json'])
    expect(apply.status, apply.stderr).toBe(0)
    expect(JSON.parse(apply.stdout).changed).toEqual(['etc/sdk.api.md'])
    expect(cli(root, ['check', '--json']).status).toBe(0)
  })

  it('reports declaration compiler failures and aborts before native tool execution', async () => {
    const root = await setup()
    await writeFile(path.join(root, 'packages/sdk/dist/index.d.ts'), 'export declare const broken: ;\n')
    expect((await checkPublicApi(root)).status).toBe('failed')
    const controller = new AbortController()
    controller.abort()
    await expect(checkPublicApi(root, { signal: controller.signal })).rejects.toThrow()
  })
})
