export const templateChoices = [
  {
    key: 'tsdown',
    label: 'tsdown 打包',
    source: 'tsdown',
    target: 'packages/tsdown',
    category: 'library',
    description: '使用 tsdown 构建的 TypeScript 库包',
  },
  {
    key: 'vue-lib',
    label: 'vue 组件',
    source: 'vue-lib',
    target: 'packages/vue-lib',
    category: 'library',
    description: 'Vue 3 组件库模板，适合沉淀可复用 UI',
  },
  {
    key: 'vue-hono',
    label: 'vue hono 全栈',
    source: 'client',
    target: 'apps/client',
    category: 'app',
    description: 'Vue 3 + Hono 的前后端一体应用模板',
  },
  {
    key: 'react-vite',
    label: 'React Vite 应用',
    source: 'react-vite',
    target: 'apps/react-vite',
    category: 'app',
    description: 'React + Vite + TypeScript 单页应用，包含交互测试与共享工程规范',
  },
  {
    key: 'hono-server',
    label: 'hono 模板',
    source: 'server',
    target: 'apps/server',
    category: 'service',
    description: 'Hono API 服务模板',
  },
  {
    key: 'vitepress',
    label: 'vitepress 文档',
    source: 'vitepress',
    target: 'apps/website',
    category: 'docs',
    description: 'VitePress 文档站模板',
  },
  {
    key: 'cli',
    label: 'cli 模板',
    source: 'cli',
    target: 'apps/cli',
    category: 'tool',
    description: 'TypeScript 命令行工具模板',
  },
  {
    key: 'nimbus',
    label: 'Nimbus 文档（默认）',
    source: 'nimbus',
    target: 'apps/docs',
    category: 'docs',
    description: '默认文档模板：Nimbus + Astro，中英双语与 AI 文档入口',
  },
  {
    key: 'react-lib',
    label: 'React 组件库',
    source: 'react-lib',
    target: 'packages/react-lib',
    category: 'library',
    description: '带类型声明、显式 CSS 出口和发布消费验证的 React 组件库',
  },
  {
    key: 'next',
    label: 'Next.js App Router 应用',
    source: 'next',
    target: 'apps/next',
    category: 'app',
    description: 'Next.js + TypeScript SSR 应用，包含客户端交互、健康接口与工作区库集成',
  },
]
