import type { Declaration } from './patterns'

// Turbo's built-in environment semantics: crates/turborepo-env/src/lib.rs.
const globalHash = ['VERCEL_ANALYTICS_ID', 'VERCEL_TARGET_ENV']
const passthrough = [
  'HOME',
  'USER',
  'TZ',
  'LANG',
  'SHELL',
  'PWD',
  'XDG_DATA_*',
  'XDG_RUNTIME_DIR',
  'XAUTHORITY',
  'DBUS_SESSION_BUS_ADDRESS',
  'CI',
  'NODE_OPTIONS',
  'COREPACK_*',
  'LD_LIBRARY_PATH',
  'DYLD_FALLBACK_LIBRARY_PATH',
  'LIBPATH',
  'LD_PRELOAD',
  'DYLD_INSERT_LIBRARIES',
  'COLORTERM',
  'FORCE_COLOR',
  'NO_COLOR',
  'TERM',
  'TERM_PROGRAM',
  'DISPLAY',
  'TMP',
  'TEMP',
  'WINDIR',
  'ProgramFiles',
  'ProgramFiles(x86)',
  'VSCODE_*',
  'ELECTRON_RUN_AS_NODE',
  'DOCKER_*',
  'BUILDKIT_*',
  'COMPOSE_*',
  'JB_IDE_*',
  'JB_INTERPRETER',
  '_JETBRAINS_TEST_RUNNER_RUN_SCOPE_TYPE',
  'TURBO_*',
  'VERCEL',
  'VERCEL_*',
  'NEXT_*',
  'USE_OUTPUT_FOR_EDGE_FUNCTIONS',
  'NOW_BUILDER',
  'VC_MICROFRONTENDS_CONFIG_FILE_NAME',
  'GITHUB_*',
  'RUNNER_*',
  '__NIXOS_*',
  'NIX_*',
  'APPDATA',
  'LOCALAPPDATA',
  'PATH',
  'PROGRAMDATA',
  'SYSTEMROOT',
  'SYSTEMDRIVE',
  'USERPROFILE',
  'HOMEDRIVE',
  'HOMEPATH',
  'PNPM_HOME',
  'pnpm_config_verify_deps_before_run',
  'NPM_CONFIG_STORE_DIR',
  'COMSPEC',
  'PATHEXT',
]

export const builtinGlobalEnv: Declaration[] = globalHash.map(pattern => ({ pattern, field: 'globalEnv', path: 'turbo:built-in' }))
export const builtinPassThroughEnv: Declaration[] = passthrough.map(pattern => ({ pattern, field: 'passThroughEnv', path: 'turbo:built-in' }))
