export { moveTemplateInstances, planTemplateInstanceMove } from './move'
export { createTemplateInstanceTarget, listTemplateInstances, prepareGeneratedTemplateInstance, rebuildTemplateInstanceBaseline, recordGeneratedTemplateInstance, relocateTemplateInstance, templateInstanceId } from './operations'
export { instanceRelativePath, safeInstancePath, templateBaselineDirectory, templateRegistryPath } from './paths'
export { replaceTemplateInstance } from './replace'
export { generationParameters, isExactTemplateVersion, normalizeTemplateExclusions } from './schema'
export { captureTemplateSnapshot, compareTemplateSnapshots, snapshotDigest, writeTemplateSnapshot } from './snapshot'
export { prepareTemplateInstanceSource, readTemplatePackageVersion } from './source'
export { canVerifyTemplateInstance, loadTemplateBaseline, loadTemplateInstanceRegistry, registerTemplateInstances } from './store'
export type { GeneratedTemplateInstanceOptions, PreparedTemplateSource, TemplateFileDifference, TemplateGenerationParameters, TemplateGenerationProfile, TemplateInstance, TemplateInstanceBaseline, TemplateInstanceDraft, TemplateInstanceInfo, TemplateInstanceMovePlan, TemplateInstanceRegistrationOptions, TemplateInstanceRegistry, TemplateInstanceReplacementHooks, TemplateInstanceSource, TemplateSnapshot, TemplateSnapshotFile } from './types'
export { recordWorkspaceTemplateInstances } from './workspace'
